apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-dev-itlusions-com
spec:
  secretName: git-dev-itlusions-com-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: git.dev.itlusions.com
  dnsNames:
    - git.dev.itlusions.nl
    - git.dev.itlusions.com