apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret-es
  namespace: default
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: gitea-admin-secret
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gitea-admin-secret
